name: Build

on:
  push:
    tags:
      - '*'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Create version file
        run: |
          VERSION=${GITHUB_REF#refs/tags/}
          echo "export const VERSION = '${VERSION}';" > dist/version.js 