name: Build

on:
  release:
    types: [created]

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4
      
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          
      - name: Create package.json
        run: |
          echo '{
            "name": "sugartv-card",
            "version": "1.0.0",
            "type": "module",
            "private": true
          }' > package.json
          
      - name: Install dependencies
        run: |
          npm install --save-dev rollup @rollup/plugin-node-resolve
          
      - name: Create version file
        run: |
          VERSION=${GITHUB_REF#refs/tags/}
          echo "export const VERSION = '${VERSION}';" > dist/version.js
          
      - name: Create rollup config
        run: |
          echo 'import { nodeResolve } from "@rollup/plugin-node-resolve";
          export default {
            input: "dist/sugartv-card.js",
            output: {
              file: "sugartv-card-bundle.js",
              format: "es"
            },
            plugins: [nodeResolve()]
          };' > rollup.config.mjs
          
      - name: Bundle JS files
        run: npx rollup -c rollup.config.mjs
          
      - name: Upload Release Asset
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ github.event.release.upload_url }}
          asset_path: ./sugartv-card-bundle.js
          asset_name: sugartv-card-bundle.js
          asset_content_type: application/javascript 