name: Build

on:
  push:
    branches:
      - '**'
    tags:
      - 'v*'
  pull_request:

jobs:
  build:
    runs-on: ubuntu-22.04
    permissions:
      contents: write
    outputs:
      build_success: ${{ steps.build_status.id }}
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0  # Needed to get all tags for versioning

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Build
        run: npm run build

      - name: Set build status
        id: build_status
        run: echo "::set-output name=status::success"

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: dist
          path: dist/
          
      - name: Create Release
        if: startsWith(github.ref, 'refs/tags/v')
        uses: softprops/action-gh-release@v1
        with:
          files: dist/*
          draft: false
          prerelease: false 