name: Build

on:
  release:
    types: [created]

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4
      
      - name: Create version file
        run: |
          VERSION=${GITHUB_REF#refs/tags/}
          echo "export const VERSION = '${VERSION}';" > dist/version.js
          
      - name: Upload Release Asset
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ github.event.release.upload_url }}
          asset_path: ./dist/version.js
          asset_name: version.js
          asset_content_type: application/javascript 