name: Build

on:
  push:
    branches:
      - '**'
    tags:
      - 'v*'
  pull_request:

jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0  # Needed to get all tags for versioning

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Build
        run: npm run build

      - name: Upload repository
        uses: actions/upload-artifact@v4
        with:
          name: repository
          path: .
          
      - name: Create Release
        if: startsWith(github.ref, 'refs/tags/v')
        uses: softprops/action-gh-release@v1
        with:
          files: dist/*
          draft: false
          prerelease: false

  validate:
    needs: build
    runs-on: ubuntu-22.04
    steps:
      - name: Download repository
        uses: actions/download-artifact@v4
        with:
          name: repository
          path: .

      - name: HACS Action
        uses: hacs/action@main
        with:
          category: "plugin"

      - name: HACS Validate
        uses: hacs/action@main
        with:
          category: "plugin" 