name: Release

on:
  push:
    tags:
      - '*'

jobs:
  build:
    uses: ./.github/workflows/build.yml

  release:
    needs: build
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4
      
      - name: Create Release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          VERSION=${GITHUB_REF#refs/tags/}
          gh release create $VERSION \
            dist/sugartv-card.js \
            dist/sugartv-card-editor.js \
            dist/sugartv-card-styles.js \
            dist/version.js \
            --title "Release $VERSION" \
            --generate-notes 